-- ML CERT SCHEMA
-- SCHEMA: ml_cert

-- DROP SCHEMA IF EXISTS ml_cert ;

CREATE SCHEMA IF NOT EXISTS ml_cert
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ml_cert TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;