-- ML SIT SCHEMA

-- SCHEMA: ml_sit

-- DROP SCHEMA IF EXISTS ml_sit ;

CREATE SCHEMA IF NOT EXISTS ml_sit
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ml_sit TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_sit
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_sit
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_sit
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_sit
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

