-- ML E2E SCHEMA
-- SCHEMA: ml_e2e

-- DROP SCHEMA IF EXISTS ml_e2e ;

CREATE SCHEMA IF NOT EXISTS ml_e2e
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ml_e2e TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_e2e
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_e2e
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_e2e
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_e2e
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- ML CERT SCHEMA
-- SCHEMA: ml_cert

-- DROP SCHEMA IF EXISTS ml_cert ;

CREATE SCHEMA IF NOT EXISTS ml_cert
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ml_cert TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_cert
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;

-- ML PROD SCHEMA
-- SCHEMA: ml_prod

-- DROP SCHEMA IF EXISTS ml_prod ;

CREATE SCHEMA IF NOT EXISTS ml_prod
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ml_prod TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;