-- ML PROD SCHEMA
-- SCHEMA: ml_prod

-- DROP SCHEMA IF EXISTS ml_prod ;

CREATE SCHEMA IF NOT EXISTS ml_prod
    AUTHORIZATION postgres;

GRANT ALL ON SCHEMA ml_prod TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT EXECUTE ON FUNCTIONS TO postgres WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA ml_prod
GRANT USAGE ON TYPES TO postgres WITH GRANT OPTION;